version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: chapter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_DATABASE=test
      - DB_USERNAME=root
      - DB_PASSWORD=root
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-net

  db:
    image: mysql:5.7
    container_name: chapter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend-net

  redis:
    image: redis:alpine
    container_name: chapter_redis
    ports:
      - "6379:6379"
    networks:
      - backend-net

volumes:
  dbdata:

networks:
  backend-net:
    driver: bridge
